/*
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by dev.tamnguyen.tool.GenerateAst
 * Generated on 2025-08-11T06:30:38.187777506Z
*/

package dev.tamnguyen.lox;

import java.util.List;
import javax.annotation.processing.Generated;
import lombok.Getter;
import lombok.AllArgsConstructor;

/**
 * Abstract syntax tree node
 *
 */
@Generated(
    value="dev.tamnguyen.tool.GenerateAst",
    date="2025-08-11T06:30:38.187777506Z",
    comments = "Do not modify this class."
)
public abstract class Stmt {
    public interface Visitor<R> {
        R visitBlockStmt(Block stmt);
        R visitExpressionStmt(Expression stmt);
        R visitIfStmt(If stmt);
        R visitPrintStmt(Print stmt);
        R visitVarStmt(Var stmt);
    }

    @AllArgsConstructor
    @Getter
    public static class Block extends Stmt {
        private final List<Stmt> statements;

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitBlockStmt(this);
        }
    }

    @AllArgsConstructor
    @Getter
    public static class Expression extends Stmt {
        private final Expr expression;

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitExpressionStmt(this);
        }
    }

    @AllArgsConstructor
    @Getter
    public static class If extends Stmt {
        private final Expr condition;
        private final Stmt thenBranch;
        private final Stmt elseBranch;

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitIfStmt(this);
        }
    }

    @AllArgsConstructor
    @Getter
    public static class Print extends Stmt {
        private final Expr expression;

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitPrintStmt(this);
        }
    }

    @AllArgsConstructor
    @Getter
    public static class Var extends Stmt {
        private final Token name;
        private final Expr initializer;

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitVarStmt(this);
        }
    }


    public abstract <R> R accept(Visitor<R> visitor);
}
