/*
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by dev.tamnguyen.tool.GenerateAst
 * Generated on 2025-08-11T02:22:03.936411276Z
*/

package dev.tamnguyen.lox;

import java.util.List;
import javax.annotation.processing.Generated;
import lombok.Getter;
import lombok.AllArgsConstructor;

/**
 * Abstract syntax tree node
 *
 */
@Generated(
    value="dev.tamnguyen.tool.GenerateAst",
    date="2025-08-11T02:22:03.936411276Z",
    comments = "Do not modify this class."
)
public abstract class Stmt {
    public interface Visitor<R> {
        R visitExpressionStmt(Expression stmt);
        R visitPrintStmt(Print stmt);
    }

    @AllArgsConstructor
    @Getter
    public static class Expression extends Stmt {
        private final Expr expression;

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitExpressionStmt(this);
        }
    }

    @AllArgsConstructor
    @Getter
    public static class Print extends Stmt {
        private final Expr expression;

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitPrintStmt(this);
        }
    }


    public abstract <R> R accept(Visitor<R> visitor);
}
